```{r}
library(shiny)
library(shinydashboard)
library(DT)
library(RPostgreSQL)
library(DBI)
library(shiny)
library(RPostgreSQL) 
library(DT)
library(rsconnect)
library(shinydashboard)
library(dygraphs)
library(fmsb)
library(modules)
library(rworldmap)
library(shiny.fluent)
library(shiny.router)
library(shinythemes)
#library(echarts4r.maps)
```


```{r}
library(ggplot2)
library(bs4Dash)
library(googlesheets4)
library(tidyverse)
library(highcharter)
library(waiter)
library(DT)
library(tidytext)
library(ggwordcloud)
library(jsonlite)
library(hackeRnews)
library(urltools)
library(shiny)
library(wordcloud)
library(tm)
library(dplyr)
library(shinyWidgets)
library(stopwords)
library(RColorBrewer)
library(plotly)
```

```{r}
# Server logic
server <- function(input, output, session) {
  # Render data tables
  output$top_wisata <- renderUI({
    wisata <- data.frame(
      nama_wisata = c("Balon Udara", "Taman Safari Indonesia", "Wana Wisata Puncak Sempur", "Situ Mustika"),
      Nama_Kabkot = c("Kab. Subang", "Kab. Bogor", "Kab. Karawang", "Kota Banjar "),
      rating = c(5, 4.9, 4.8),
      image = c(
        "https://www.akurat.co/travel/1302347301/Ada-Wisata-Balon-Udara-Ala-Cappadocia-di-Ciater-Subang-Ini-Biayanya", 
        "https://edensorhills.com/wp-content/uploads/2022/12/Taman-Safari-Indonesia-Bogor-1024x576.jpg ", 
        "https://bandung.kompas.com/image/2023/01/04/211001778/puncak-sempur-di-karawang-daya-tarik-jam-buka-harga-tiket-dan-rute?page=2
", "ttps://www.harapanrakyat.com/2020/06/wana-wisata-situ-mustika-kota-banjar-kembali-dibuka-ada-diskon-tiket-masuk/ "
      )
    )
    
    book_panels <- lapply(1:nrow(books_data), function(i) {
      # Jumlah bintang penuh berdasarkan pembulatan ke bawah dari rating
      bintang_penuh <- floor(books_data$rating[i])
      # Menentukan apakah ada setengah bintang
      setengah_bintang <- ifelse((books_data$rating[i]*2) %% 2 != 0, 1, 0)
      # Menghitung jumlah bintang kosong
      bintang_kosong <- 5 - bintang_penuh - setengah_bintang
      
      # Membangun HTML untuk bintang-bintang
      stars_html <- paste0(
        strrep('<i class="fa fa-star"></i>', bintang_penuh),
        ifelse(setengah_bintang > 0, '<i class="fa fa-star-half-o"></i>', ''),
        strrep('<i class="fa fa-star-o"></i>', bintang_kosong),
        collapse = ""
      )
      
      column(4, class = "top-book-panel",
             tags$img(src = books_data$image[i], height = "150px"),
             tags$p(strong(books_data$title[i]), 
                    tags$br(), 
                    "by ", books_data$author[i]),
             tags$div(class = "rating", 
                      HTML(stars_html)
             )
      )
    })
    
    do.call(fluidRow, book_panels)
  })

 # Awalnya, kita perlu memuat pilihan awal untuk semua input
  observe({
    # Perlu query untuk mengambil semua Nama_Kabkot dan Tipe_Wisata
    Nama_Kabkot <- readData("SELECT DISTINCT Nama_Kabkot FROM kabupaten ORDER BY Nama_Kabkot")
    Tipe_Wisata <- readData("SELECT DISTINCT Tipe_Wisata FROM wisata ORDER BY Tipe_Wisata")
    
 updateSelectInput(session, "KabkotInput", choices = c("", kabupaten$Nama_Kabkot))
    updateSelectInput(session, "TipeInput", choices = c("", wisata$Tipe_Wisata))
  })
}
```

```{r}
# Ketika Nama_Kabkot dipilih, perbarui pilihan Tipe_Wisata
observeEvent(input$namaKabkotInput, {
  if (input$namaKabkotInput != "") {
    query <- sprintf(
      "SELECT DISTINCT Tipe_Wisata 
       FROM wisata 
       JOIN kabupaten ON wisata.id_kabkot = kabupaten.id_kabkot
       WHERE kabupaten.Nama_Kabkot = '%s'", input$namaKabkotInput
    )
    related_data <- readData(query)

    # Perbarui pilihan Tipe_Wisata berdasarkan hasil query
    updateSelectInput(session, "tipeWisataInput", choices = c("", related_data$tipe_wisata))
  } else {
    # Jika Nama_Kabkot dikosongkan, reset pilihan Tipe_Wisata
    updateSelectInput(session, "tipeWisataInput", selected = NULL)
  }
})

```

```{r}
 # Membangun dan menjalankan query baru ketika tombol "Cari" diklik
  observeEvent(input$searchButton, {
    withProgress(message = 'Mohon tunggu...', value = 0, {
      # Setel ulang indikator pemuatan ke nilai 0
      setProgress(value = 0, message = "Sedang memuat data...")
       query <- constructQuery(input$namaKabkotInput, input$tipeWisataInput)
      output$searchResultsTable <- renderDT({
        datatable(readData(query), options = list(
          lengthChange = TRUE, 
          pageLength = 10, 
          lengthMenu = list(c(10, 25, 50, 100), c('10', '25', '50', '100')), 
          searching = TRUE, 
          info = TRUE,
          autoWidth = TRUE,
          columnDefs = list(
            list(
              targets = 4, # Sesuaikan indeks ini jika struktur tabel Anda berubah
              render = JS(
                "function(data, type, row, meta) {
                if(type === 'display' && data != null && data != '') {
                  return '<a href=\"' + data + '\" target=\"_blank\">' + data + '</a>';
                } else {
                  return data;
                }
              }"
              )
            )
          )
        ), escape = FALSE
        )
      }, server = FALSE) # Menonaktifkan processing server-side
      # Selesaikan indikator pemuatan
      setProgress(value = 1)
    })
  })
  
```

```{r}
# Grafik Interaktif untuk Eksplorasi Data Wisata per Kabupaten
output$interactivePlot <- renderPlotly({
  
  # Query untuk mengambil jumlah wisata dan rata-rata pengunjung per kabupaten
  query <- "
  SELECT w.Nama_KabKota, 
         COUNT(*) AS jumlah_wisata, 
         AVG(CAST(w.jumlah_pengunjung AS INTEGER)) AS avg_pengunjung
  FROM wisata w
  GROUP BY w.Nama_KabKota
  ORDER BY jumlah_wisata DESC
  "
  
  # Membaca data dari database
  data <- readData(query)

  # Plot data wisata per kabupaten
  plot_ly(data, 
          x = ~Nama_KabKota, 
          y = ~jumlah_wisata, 
          type = 'bar', 
          name = 'Jumlah Wisata') %>%
    
    add_trace(y = ~avg_pengunjung, 
              name = 'Rata-rata Pengunjung', 
              mode = 'lines+markers') %>%
    
    layout(yaxis2 = list(overlaying = "y", side = "right"))
})
```

